name: "🏗️ Build Plugin"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
    tags:
      - "v*"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@master

  release:
    needs: call
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
